#include "http_common_field_lines.h"

#include <string.h>

//IANA registry of field line names
//https://www.iana.org/assignments/http-fields/http-fields.xhtml
//When modifying this array keep lexicographical order by field_name
//it is used in binary search
const Field_line_attributes_t __common_field_lines_attributes__[] = {
    {"",                                            UNKNOWN_TYPE},
    {"A-IM",                                        LIST},
    {"Accept",                                      LIST},
    {"Accept-Additions",                            LIST},
    {"Accept-CH",                                   LIST},
    {"Accept-Charset",                              LIST},
    {"Accept-Datetime",                             SINGLETON},
    {"Accept-Encoding",                             LIST},
    {"Accept-Features",                             LIST},
    {"Accept-Language",                             LIST},
    {"Accept-Patch",                                LIST_NONEMPTY},
    {"Accept-Post",                                 LIST},
    {"Accept-Query",                                LIST},
    {"Accept-Ranges",                               LIST_NONEMPTY},
    {"Accept-Signature",                            LIST},
    {"Access-Control",                              LIST_NONEMPTY},
    {"Access-Control-Allow-Credentials",            SINGLETON},
    {"Access-Control-Allow-Headers",                LIST},
    {"Access-Control-Allow-Methods",                SINGLETON},
    {"Access-Control-Allow-Origin",                 SINGLETON},
    {"Access-Control-Expose-Headers",               LIST},
    {"Access-Control-Max-Age",                      SINGLETON},
    {"Access-Control-Request-Headers",              LIST_NONEMPTY},
    {"Access-Control-Request-Method",               SINGLETON},
    {"Activate-Storage-Access",                     SINGLETON},
    {"Age",                                         SINGLETON},
    {"Allow",                                       LIST},
    {"ALPN",                                        LIST_NONEMPTY},
    {"Alt-Svc",                                     LIST_NONEMPTY},
    {"Alt-Used",                                    SINGLETON},
    {"Alternates",                                  LIST_NONEMPTY},
    {"AMP-Cache-Transform",                         LIST_NONEMPTY},
    {"Apply-To-Redirect-Ref",                       SINGLETON},
    {"Authentication-Control",                      LIST_NONEMPTY},
    {"Authentication-Info",                         LIST},
    {"Authorization",                               SINGLETON},
    {"Available-Dictionary",                        SINGLETON},
    {"C-Ext",                                       SINGLETON},
    {"C-Man",                                       LIST_NONEMPTY},
    {"C-Opt",                                       LIST_NONEMPTY},
    {"C-PEP",                                       LIST_NONEMPTY},
    {"C-PEP-Info",                                  LIST_NONEMPTY},
    {"Cache-Control",                               LIST},
    {"Cache-Group-Invalidation",                    LIST},
    {"Cache-Groups",                                LIST},
    {"Cache-Status",                                LIST},
    {"Cal-Managed-ID",                              SINGLETON},
    {"CalDAV-Timezones",                            SINGLETON},
    {"Capsule-Protocol",                            SINGLETON},
    {"CDN-Cache-Control",                           LIST_NONEMPTY},
    {"CDN-Loop",                                    LIST},
    {"Cert-Not-After",                              SINGLETON},
    {"Cert-Not-Before",                             SINGLETON},
    {"Clear-Site-Data",                             LIST_NONEMPTY},
    {"Client-Cert",                                 SINGLETON},
    {"Client-Cert-Chain",                           LIST_NONEMPTY},
    {"CMCD-Object",                                 LIST},
    {"CMCD-Request",                                LIST},
    {"CMCD-Session",                                LIST},
    {"CMCD-Status",                                 LIST},
    {"CMSD-Dynamic",                                LIST_NONEMPTY},
    {"CMSD-Static",                                 LIST_NONEMPTY},
    {"Concealed-Auth-Export",                       SINGLETON},
    {"Configuration-Context",                       SINGLETON},
    {"Connection",                                  LIST},
    {"Content-Base",                                SINGLETON},
    {"Content-Digest",                              LIST_NONEMPTY},
    {"Content-Disposition",                         SINGLETON},
    {"Content-Encoding",                            LIST},
    {"Content-ID",                                  SINGLETON},
    {"Content-Language",                            LIST},
    {"Content-Length",                              SINGLETON_WITH_DEDUPLICATION},
    {"Content-Location",                            SINGLETON},
    {"Content-MD5",                                 SINGLETON},
    {"Content-Range",                               SINGLETON},
    {"Content-Script-Type",                         SINGLETON},
    {"Content-Security-Policy",                     LIST_NONEMPTY},
    {"Content-Security-Policy-Report-Only",         LIST_NONEMPTY},
    {"Content-Style-Type",                          SINGLETON},
    {"Content-Type",                                SINGLETON},
    {"Content-Version",                             SINGLETON},
    {"Cookie",                                      MULTILINE_DO_NOT_MERGE},
    {"Cookie2",                                     SINGLETON},
    {"Cross-Origin-Embedder-Policy",                SINGLETON},
    {"Cross-Origin-Embedder-Policy-Report-Only",    SINGLETON},
    {"Cross-Origin-Opener-Policy",                  SINGLETON},
    {"Cross-Origin-Opener-Policy-Report-Only",      SINGLETON},
    {"Cross-Origin-Resource-Policy",                SINGLETON},
    {"CTA-Common-Access-Token",                     SINGLETON},
    {"DASL",                                        LIST_NONEMPTY},
    {"Date",                                        SINGLETON},
    {"DAV",                                         LIST},
    {"Default-Style",                               SINGLETON},
    {"Delta-Base",                                  SINGLETON},
    {"Deprecation",                                 SINGLETON},
    {"Depth",                                       SINGLETON},
    {"Derived-From",                                SINGLETON},
    {"Destination",                                 SINGLETON},
    {"Detached-JWS",                                SINGLETON},
    {"Differential-ID",                             SINGLETON},
    {"Dictionary-ID",                               SINGLETON},
    {"Digest",                                      LIST},
    {"DPoP",                                        SINGLETON},
    {"DPoP-Nonce",                                  SINGLETON},
    {"Early-Data",                                  SINGLETON},
    {"EDIINT-Features",                             LIST_NONEMPTY},
    {"ETag",                                        SINGLETON},
    {"Expect",                                      LIST},
    {"Expect-CT",                                   LIST_NONEMPTY},
    {"Expires",                                     SINGLETON},
    {"Ext",                                         SINGLETON},
    {"Forwarded",                                   LIST_NONEMPTY},
    {"From",                                        SINGLETON},
    {"GetProfile",                                  SINGLETON},
    {"Hobareg",                                     SINGLETON},
    {"Host",                                        SINGLETON},
    {"HTTP2-Settings",                              SINGLETON},
    {"If",                                          SINGLETON},
    {"If-Match",                                    LIST_NONEMPTY},
    {"If-Modified-Since",                           SINGLETON},
    {"If-None-Match",                               LIST_NONEMPTY},
    {"If-Range",                                    SINGLETON},
    {"If-Schedule-Tag-Match",                       SINGLETON},
    {"If-Unmodified-Since",                         SINGLETON},
    {"IM",                                          LIST},
    {"Include-Referred-Token-Binding-ID",           SINGLETON},
    {"Incremental",                                 SINGLETON},
    {"Isolation",                                   SINGLETON},
    {"Keep-Alive",                                  LIST},
    {"Label",                                       SINGLETON},
    {"Last-Event-ID",                               SINGLETON},
    {"Last-Modified",                               SINGLETON},
    {"Link",                                        LIST},
    {"Link-Template",                               LIST_NONEMPTY},
    {"Location",                                    SINGLETON},
    {"Lock-Token",                                  SINGLETON},
    {"Man",                                         LIST_NONEMPTY},
    {"Max-Forwards",                                SINGLETON},
    {"Memento-Datetime",                            SINGLETON},
    {"Meter",                                       LIST},
    {"Method-Check",                                SINGLETON},
    {"Method-Check-Expires",                        SINGLETON},
    {"MIME-Version",                                SINGLETON},
    {"Negotiate",                                   LIST_NONEMPTY},
    {"NEL",                                         SINGLETON},
    {"OData-EntityId",                              SINGLETON},
    {"OData-Isolation",                             SINGLETON},
    {"OData-MaxVersion",                            SINGLETON},
    {"OData-Version",                               SINGLETON},
    {"Opt",                                         LIST_NONEMPTY},
    {"Optional-WWW-Authenticate",                   LIST_NONEMPTY},
    {"Ordering-Type",                               SINGLETON},
    {"Origin",                                      SINGLETON},
    {"Origin-Agent-Cluster",                        SINGLETON},
    {"OSCORE",                                      SINGLETON},
    {"OSLC-Core-Version",                           SINGLETON},
    {"Overwrite",                                   SINGLETON},
    {"P3P",                                         LIST_NONEMPTY},
    {"PEP",                                         LIST_NONEMPTY},
    {"PEP-Info",                                    LIST_NONEMPTY},
    {"Permissions-Policy",                          LIST_NONEMPTY},
    {"PICS-Label",                                  SINGLETON},
    {"Ping-From",                                   SINGLETON},
    {"Ping-To",                                     SINGLETON},
    {"Position",                                    SINGLETON},
    {"Pragma",                                      SINGLETON},
    {"Prefer",                                      LIST_NONEMPTY},
    {"Preference-Applied",                          LIST_NONEMPTY},
    {"Priority",                                    LIST_NONEMPTY},
    {"ProfileObject",                               SINGLETON},
    {"Protocol",                                    LIST_NONEMPTY},
    {"Protocol-Info",                               LIST_NONEMPTY},
    {"Protocol-Query",                              LIST_NONEMPTY},
    {"Protocol-Request",                            LIST_NONEMPTY},
    {"Proxy-Authenticate",                          LIST},
    {"Proxy-Authentication-Info",                   LIST},
    {"Proxy-Authorization",                         SINGLETON},
    {"Proxy-Features",                              SINGLETON},
    {"Proxy-Instruction",                           SINGLETON},
    {"Proxy-Status",                                LIST_NONEMPTY},
    {"Public",                                      LIST_NONEMPTY},
    {"Public-Key-Pins",                             SINGLETON},
    {"Public-Key-Pins-Report-Only",                 SINGLETON},
    {"Range",                                       SINGLETON},
    {"Redirect-Ref",                                SINGLETON},
    {"Referer",                                     SINGLETON},
    {"Referer-Root",                                SINGLETON},
    {"Referrer-Policy",                             LIST_NONEMPTY},
    {"Refresh",                                     SINGLETON},
    {"Repeatability-Client-ID",                     SINGLETON},
    {"Repeatability-First-Sent",                    SINGLETON},
    {"Repeatability-Request-ID",                    SINGLETON},
    {"Repeatability-Result",                        SINGLETON},
    {"Replay-Nonce",                                SINGLETON},
    {"Reporting-Endpoints",                         LIST_NONEMPTY},
    {"Repr-Digest",                                 LIST_NONEMPTY},
    {"Retry-After",                                 SINGLETON},
    {"Safe",                                        SINGLETON},
    {"Schedule-Reply",                              SINGLETON},
    {"Schedule-Tag",                                SINGLETON},
    {"Sec-Fetch-Dest",                              SINGLETON},
    {"Sec-Fetch-Mode",                              SINGLETON},
    {"Sec-Fetch-Site",                              SINGLETON},
    {"Sec-Fetch-Storage-Access",                    SINGLETON},
    {"Sec-Fetch-User",                              SINGLETON},
    {"Sec-GPC",                                     SINGLETON},
    {"Sec-Purpose",                                 SINGLETON},
    {"Sec-Token-Binding",                           SINGLETON},
    {"Sec-WebSocket-Accept",                        SINGLETON},
    {"Sec-WebSocket-Extensions",                    LIST_NONEMPTY},
    {"Sec-WebSocket-Key",                           SINGLETON},
    {"Sec-WebSocket-Protocol",                      LIST_NONEMPTY},
    {"Sec-WebSocket-Version",                       LIST_NONEMPTY},
    {"Security-Scheme",                             SINGLETON},
    {"Server",                                      SINGLETON},
    {"Server-Timing",                               LIST},
    {"Set-Cookie",                                  MULTILINE_DO_NOT_MERGE},
    {"Set-Cookie2",                                 MULTILINE_DO_NOT_MERGE},
    {"Set-Txn",                                     SINGLETON},
    {"SetProfile",                                  SINGLETON},
    {"Signature",                                   LIST_NONEMPTY},
    {"Signature-Input",                             LIST_NONEMPTY},
    {"SLUG",                                        SINGLETON},
    {"SoapAction",                                  SINGLETON},
    {"Status-URI",                                  SINGLETON},
    {"Strict-Transport-Security",                   SINGLETON},
    {"Sunset",                                      SINGLETON},
    {"Surrogate-Capability",                        LIST_NONEMPTY},
    {"Surrogate-Control",                           LIST_NONEMPTY},
    {"TCN",                                         LIST},
    {"TE",                                          LIST},
    {"Timeout",                                     LIST_NONEMPTY},
    {"Timing-Allow-Origin",                         LIST_NONEMPTY},
    {"Topic",                                       SINGLETON},
    {"Traceparent",                                 SINGLETON},
    {"Tracestate",                                  LIST},
    {"Trailer",                                     LIST},
    {"Transfer-Encoding",                           LIST},
    {"TTL",                                         SINGLETON},
    {"Upgrade",                                     LIST},
    {"Urgency",                                     SINGLETON},
    {"URI",                                         LIST_NONEMPTY},
    {"Use-As-Dictionary",                           LIST_NONEMPTY},
    {"User-Agent",                                  SINGLETON},
    {"Variant-Vary",                                LIST_NONEMPTY},
    {"Vary",                                        LIST},
    {"Via",                                         LIST},
    {"Want-Content-Digest",                         LIST_NONEMPTY},
    {"Want-Digest",                                 LIST},
    {"Want-Repr-Digest",                            LIST_NONEMPTY},
    {"Warning",                                     SNIGLETON},
    {"WWW-Authenticate",                            LIST},
    {"X-Content-Type-Options",                      SINGLETON},
    {"X-Frame-Options",                             SINGLETON}
};

const size_t __common_field_lines_count__ =
                            sizeof(__common_field_lines_attributes__) /
                            sizeof(__common_field_lines_attributes__[0]);

extern const Field_line_attributes_t* common_field_lines_attributes =
                            __common_field_lines_attributes__;
extern const size_t common_field_lines_count =
                            __common_field_lines_count__;

Field_line_attributes_t* find_field_line_attributes(const char* field_name) {
    size_t l = 0, h = common_field_lines_count - 1;
    while (l <= h) {
        size_t m = l + (h - l) / 2;
        if (strcasecmp(common_field_lines_attributes[m].field_name, field_name) < 0) {
            l = m + 1;
        }
        else if (strcasecmp(common_field_lines_attributes[m].field_name, field_name) > 0) {
            h = m - 1;
        }
        else {
            return &common_field_lines_attributes[m];
        }
    }
    //If we didn't find field_name we return 0-th element,
    //it is a placeholder for unknown field line name
    return &common_field_lines_attributes[0];
}

