#include "http_common_field_lines.h"

#include <string.h>

//IANA registry of field line names
//https://www.iana.org/assignments/http-fields/http-fields.xhtml
//When modifying this array keep lexicographical order by field_name
//it is used in binary search
const Field_line_attributes_t __common_field_lines_attributes__[] = {
    {"",                                            UNKNOWN_TYPE},
    {"a-im",                                        LIST},
    {"accept",                                      LIST},
    {"accept-additions",                            LIST},
    {"accept-ch",                                   LIST},
    {"accept-charset",                              LIST},
    {"accept-datetime",                             SINGLETON},
    {"accept-encoding",                             LIST},
    {"accept-features",                             LIST},
    {"accept-language",                             LIST},
    {"accept-patch",                                LIST_NONEMPTY},
    {"accept-post",                                 LIST},
    {"accept-query",                                LIST},
    {"accept-ranges",                               LIST_NONEMPTY},
    {"accept-signature",                            LIST},
    {"access-control",                              LIST_NONEMPTY},
    {"access-control-allow-credentials",            SINGLETON},
    {"access-control-allow-headers",                LIST},
    {"access-control-allow-methods",                SINGLETON},
    {"access-control-allow-origin",                 SINGLETON},
    {"access-control-expose-headers",               LIST},
    {"access-control-max-age",                      SINGLETON},
    {"access-control-request-headers",              LIST_NONEMPTY},
    {"access-control-request-method",               SINGLETON},
    {"activate-storage-access",                     SINGLETON},
    {"age",                                         SINGLETON},
    {"allow",                                       LIST},
    {"alpn",                                        LIST_NONEMPTY},
    {"alt-svc",                                     LIST_NONEMPTY},
    {"alt-used",                                    SINGLETON},
    {"alternates",                                  LIST_NONEMPTY},
    {"amp-cache-transform",                         LIST_NONEMPTY},
    {"apply-to-redirect-ref",                       SINGLETON},
    {"authentication-control",                      LIST_NONEMPTY},
    {"authentication-info",                         LIST},
    {"authorization",                               SINGLETON},
    {"available-dictionary",                        SINGLETON},
    {"c-ext",                                       SINGLETON},
    {"c-man",                                       LIST_NONEMPTY},
    {"c-opt",                                       LIST_NONEMPTY},
    {"c-pep",                                       LIST_NONEMPTY},
    {"c-pep-info",                                  LIST_NONEMPTY},
    {"cache-control",                               LIST},
    {"cache-group-invalidation",                    LIST},
    {"cache-groups",                                LIST},
    {"cache-status",                                LIST},
    {"cal-managed-id",                              SINGLETON},
    {"caldav-timezones",                            SINGLETON},
    {"capsule-protocol",                            SINGLETON},
    {"cdn-cache-control",                           LIST_NONEMPTY},
    {"cdn-loop",                                    LIST},
    {"cert-not-after",                              SINGLETON},
    {"cert-not-before",                             SINGLETON},
    {"clear-site-data",                             LIST_NONEMPTY},
    {"client-cert",                                 SINGLETON},
    {"client-cert-chain",                           LIST_NONEMPTY},
    {"cmcd-object",                                 LIST},
    {"cmcd-request",                                LIST},
    {"cmcd-session",                                LIST},
    {"cmcd-status",                                 LIST},
    {"cmsd-dynamic",                                LIST_NONEMPTY},
    {"cmsd-static",                                 LIST_NONEMPTY},
    {"concealed-auth-export",                       SINGLETON},
    {"configuration-context",                       SINGLETON},
    {"connection",                                  LIST},
    {"content-base",                                SINGLETON},
    {"content-digest",                              LIST_NONEMPTY},
    {"content-disposition",                         SINGLETON},
    {"content-encoding",                            LIST},
    {"content-id",                                  SINGLETON},
    {"content-language",                            LIST},
    {"content-length",                              SINGLETON_WITH_DEDUPLICATION},
    {"content-location",                            SINGLETON},
    {"content-md5",                                 SINGLETON},
    {"content-range",                               SINGLETON},
    {"content-script-type",                         SINGLETON},
    {"content-security-policy",                     LIST_NONEMPTY},
    {"content-security-policy-report-only",         LIST_NONEMPTY},
    {"content-style-type",                          SINGLETON},
    {"content-type",                                SINGLETON},
    {"content-version",                             SINGLETON},
    {"cookie",                                      MULTILINE_DO_NOT_MERGE},
    {"cookie2",                                     SINGLETON},
    {"cross-origin-embedder-policy",                SINGLETON},
    {"cross-origin-embedder-policy-report-only",    SINGLETON},
    {"cross-origin-opener-policy",                  SINGLETON},
    {"cross-origin-opener-policy-report-only",      SINGLETON},
    {"cross-origin-resource-policy",                SINGLETON},
    {"cta-common-access-token",                     SINGLETON},
    {"dasl",                                        LIST_NONEMPTY},
    {"date",                                        SINGLETON},
    {"dav",                                         LIST},
    {"default-style",                               SINGLETON},
    {"delta-base",                                  SINGLETON},
    {"deprecation",                                 SINGLETON},
    {"depth",                                       SINGLETON},
    {"derived-from",                                SINGLETON},
    {"destination",                                 SINGLETON},
    {"detached-jws",                                SINGLETON},
    {"differential-id",                             SINGLETON},
    {"dictionary-id",                               SINGLETON},
    {"digest",                                      LIST},
    {"dpop",                                        SINGLETON},
    {"dpop-nonce",                                  SINGLETON},
    {"early-data",                                  SINGLETON},
    {"ediint-features",                             LIST_NONEMPTY},
    {"etag",                                        SINGLETON},
    {"expect",                                      LIST},
    {"expect-ct",                                   LIST_NONEMPTY},
    {"expires",                                     SINGLETON},
    {"ext",                                         SINGLETON},
    {"forwarded",                                   LIST_NONEMPTY},
    {"from",                                        SINGLETON},
    {"getprofile",                                  SINGLETON},
    {"hobareg",                                     SINGLETON},
    {"host",                                        SINGLETON},
    {"http2-settings",                              SINGLETON},
    {"if",                                          SINGLETON},
    {"if-match",                                    LIST_NONEMPTY},
    {"if-modified-since",                           SINGLETON},
    {"if-none-match",                               LIST_NONEMPTY},
    {"if-range",                                    SINGLETON},
    {"if-schedule-tag-match",                       SINGLETON},
    {"if-unmodified-since",                         SINGLETON},
    {"im",                                          LIST},
    {"include-referred-token-binding-id",           SINGLETON},
    {"incremental",                                 SINGLETON},
    {"isolation",                                   SINGLETON},
    {"keep-alive",                                  LIST},
    {"label",                                       SINGLETON},
    {"last-event-id",                               SINGLETON},
    {"last-modified",                               SINGLETON},
    {"link",                                        LIST},
    {"link-template",                               LIST_NONEMPTY},
    {"location",                                    SINGLETON},
    {"lock-token",                                  SINGLETON},
    {"man",                                         LIST_NONEMPTY},
    {"max-forwards",                                SINGLETON},
    {"memento-datetime",                            SINGLETON},
    {"meter",                                       LIST},
    {"method-check",                                SINGLETON},
    {"method-check-expires",                        SINGLETON},
    {"mime-version",                                SINGLETON},
    {"negotiate",                                   LIST_NONEMPTY},
    {"nel",                                         SINGLETON},
    {"odata-entityid",                              SINGLETON},
    {"odata-isolation",                             SINGLETON},
    {"odata-maxversion",                            SINGLETON},
    {"odata-version",                               SINGLETON},
    {"opt",                                         LIST_NONEMPTY},
    {"optional-www-authenticate",                   LIST_NONEMPTY},
    {"ordering-type",                               SINGLETON},
    {"origin",                                      SINGLETON},
    {"origin-agent-cluster",                        SINGLETON},
    {"oscore",                                      SINGLETON},
    {"oslc-core-version",                           SINGLETON},
    {"overwrite",                                   SINGLETON},
    {"p3p",                                         LIST_NONEMPTY},
    {"pep",                                         LIST_NONEMPTY},
    {"pep-info",                                    LIST_NONEMPTY},
    {"permissions-policy",                          LIST_NONEMPTY},
    {"pics-label",                                  SINGLETON},
    {"ping-from",                                   SINGLETON},
    {"ping-to",                                     SINGLETON},
    {"position",                                    SINGLETON},
    {"pragma",                                      SINGLETON},
    {"prefer",                                      LIST_NONEMPTY},
    {"preference-applied",                          LIST_NONEMPTY},
    {"priority",                                    LIST_NONEMPTY},
    {"profileobject",                               SINGLETON},
    {"protocol",                                    LIST_NONEMPTY},
    {"protocol-info",                               LIST_NONEMPTY},
    {"protocol-query",                              LIST_NONEMPTY},
    {"protocol-request",                            LIST_NONEMPTY},
    {"proxy-authenticate",                          LIST},
    {"proxy-authentication-info",                   LIST},
    {"proxy-authorization",                         SINGLETON},
    {"proxy-features",                              SINGLETON},
    {"proxy-instruction",                           SINGLETON},
    {"proxy-status",                                LIST_NONEMPTY},
    {"public",                                      LIST_NONEMPTY},
    {"public-key-pins",                             SINGLETON},
    {"public-key-pins-report-only",                 SINGLETON},
    {"range",                                       SINGLETON},
    {"redirect-ref",                                SINGLETON},
    {"referer",                                     SINGLETON},
    {"referer-root",                                SINGLETON},
    {"referrer-policy",                             LIST_NONEMPTY},
    {"refresh",                                     SINGLETON},
    {"repeatability-client-id",                     SINGLETON},
    {"repeatability-first-sent",                    SINGLETON},
    {"repeatability-request-id",                    SINGLETON},
    {"repeatability-result",                        SINGLETON},
    {"replay-nonce",                                SINGLETON},
    {"reporting-endpoints",                         LIST_NONEMPTY},
    {"repr-digest",                                 LIST_NONEMPTY},
    {"retry-after",                                 SINGLETON},
    {"safe",                                        SINGLETON},
    {"schedule-reply",                              SINGLETON},
    {"schedule-tag",                                SINGLETON},
    {"sec-fetch-dest",                              SINGLETON},
    {"sec-fetch-mode",                              SINGLETON},
    {"sec-fetch-site",                              SINGLETON},
    {"sec-fetch-storage-access",                    SINGLETON},
    {"sec-fetch-user",                              SINGLETON},
    {"sec-gpc",                                     SINGLETON},
    {"sec-purpose",                                 SINGLETON},
    {"sec-token-binding",                           SINGLETON},
    {"sec-websocket-accept",                        SINGLETON},
    {"sec-websocket-extensions",                    LIST_NONEMPTY},
    {"sec-websocket-key",                           SINGLETON},
    {"sec-websocket-protocol",                      LIST_NONEMPTY},
    {"sec-websocket-version",                       LIST_NONEMPTY},
    {"security-scheme",                             SINGLETON},
    {"server",                                      SINGLETON},
    {"server-timing",                               LIST},
    {"set-cookie",                                  MULTILINE_DO_NOT_MERGE},
    {"set-cookie2",                                 MULTILINE_DO_NOT_MERGE},
    {"set-txn",                                     SINGLETON},
    {"setprofile",                                  SINGLETON},
    {"signature",                                   LIST_NONEMPTY},
    {"signature-input",                             LIST_NONEMPTY},
    {"slug",                                        SINGLETON},
    {"soapaction",                                  SINGLETON},
    {"status-uri",                                  SINGLETON},
    {"strict-transport-security",                   SINGLETON},
    {"sunset",                                      SINGLETON},
    {"surrogate-capability",                        LIST_NONEMPTY},
    {"surrogate-control",                           LIST_NONEMPTY},
    {"tcn",                                         LIST},
    {"te",                                          LIST},
    {"timeout",                                     LIST_NONEMPTY},
    {"timing-allow-origin",                         LIST_NONEMPTY},
    {"topic",                                       SINGLETON},
    {"traceparent",                                 SINGLETON},
    {"tracestate",                                  LIST},
    {"trailer",                                     LIST},
    {"transfer-encoding",                           LIST},
    {"ttl",                                         SINGLETON},
    {"upgrade",                                     LIST},
    {"urgency",                                     SINGLETON},
    {"uri",                                         LIST_NONEMPTY},
    {"use-as-dictionary",                           LIST_NONEMPTY},
    {"user-agent",                                  SINGLETON},
    {"variant-vary",                                LIST_NONEMPTY},
    {"vary",                                        LIST},
    {"via",                                         LIST},
    {"want-content-digest",                         LIST_NONEMPTY},
    {"want-digest",                                 LIST},
    {"want-repr-digest",                            LIST_NONEMPTY},
    {"warning",                                     SINGLETON},
    {"www-authenticate",                            LIST},
    {"x-content-type-options",                      SINGLETON},
    {"x-frame-options",                             SINGLETON}
};

const size_t __common_field_lines_count__ =
                            sizeof(__common_field_lines_attributes__) /
                            sizeof(__common_field_lines_attributes__[0]);

const Field_line_attributes_t* g_common_field_lines_attributes =
                            __common_field_lines_attributes__;
const size_t g_common_field_lines_count =
                            __common_field_lines_count__;

const Field_line_attributes_t* find_field_line_attributes(const char* field_name) {
    size_t l = 0, h = g_common_field_lines_count - 1;
    while (l <= h) {
        size_t m = l + (h - l) / 2;
        if (strcmp(g_common_field_lines_attributes[m].field_name, field_name) < 0) {
            l = m + 1;
        }
        else if (strcmp(g_common_field_lines_attributes[m].field_name, field_name) > 0) {
            h = m - 1;
        }
        else {
            return &g_common_field_lines_attributes[m];
        }
    }
    //If we didn't find field_name we return 0-th element,
    //it is a placeholder for unknown field line name
    return &g_common_field_lines_attributes[0];
}

